### ISSUE TITLE
Storing DateTimes in UTC or with timezone

### ISSUE THREAD

**Issue by heiglandreas** [Rarst/wp-date#2]
Moving the discussion away from the [roadmap](https://github.com/Rarst/wp-date/issues/1) to a separate issue.

**Comment by heiglandreas** [comment]
And while I believe that every DateTime information (any information that consists of a date as well as a time) that is more that about 2 weeks away into the future or the past from the current moment in time needs to be stored with it's timezone there might be reasons for not doing that. But that means that one needs to know the consequences to be able to reaches an informed decision of why not to do it.

I'Ve elaborated on why I think it's a good idea to **not** store said DateTimes in UTC in [a blogpost](https://andreas.heigl.org/2016/12/22/why-not-to-convert-a-datetime-to-timestamp/) I've written.

And there are also ways of using on-the-fly timezone-conversions within MySQL to compare DateTimes from different timezones with one another. I've also [covered them](https://heiglandreas.github.io/slidedeck/time_is_an_illusion/20180609-dpc/index_online.html#/37) in a talk of mine. 

That should make it possible to handle DateTimes rather well.

Though as this is about a DateTime-Class for WordPress, two important thing needs to be taken into account: 

* WordPress can be used on systems that do not receive regular system-updates 
* WordPress can be used on systems where the MySQL-Database is not completely under the administration of the WordPress-Admin

Why are those issues?  The simple answer: Because Timezones change. Due to that the timezone-database changes. And those changes need to reach the server. And the MySQL-Server. Otherwise it's like converting money with a week old exchange-rate table. You will not get the right values during conversion.

So when it can not be assured that the WordPress-installation runs on an OS that always gets the current timezone-database and where those updates also reach the MySQL-Server, then there is no way of reliably converting between timezones. 

Therefore **all** timezone-conversions on such systems are broken to a certain extend and it might be better to completely remove timezones out of that equation and only use local time. Not even UTC as the conversion from local time to UTC might be broken at one point due to not-updated timezone-informations…

**Comment by Rarst** [comment]
Thank you, I was just getting to making an issue. :)

First, small note — this project is not about introducing new object abstraction to WP. I already have one in WpDateTime and frankly it won't work out on PHP 5.2. The goals are to deal with a mess, which might or might not take introducing new objects in the end.

Back to the issue.

From my experience with the topic at the moment **I believe WP needs to make UTC times canonical**.

## Current time data storage

Historically WP stores two DATETIME fields `YYYY-MM-DD HH:MM:SS` in database — with local time at the time of saving and UTC time (mis–named GMT in schema, but close enough). The former very notably lacks time zone information.

For the latter it’s great to _have_ UTC time, but it’s _not guaranteed_ to be filled and not guaranteed to be valid. WP uses local time as canonical, and UTC time is a bit of an optional afterthought.

## Losing context issue

The huge problem is that it only ever works **if settings time zone never ever changes**. Changing time zone in WP settings **invalidates local time on every post ever made**.

Blown up to general case — WP site might contain arbitrary amount of posts records, made in arbitrary amount of timezones. Of which only posts that were made in _current_ time zone happen to have valid local time data.

## Queries issue

On top of that even if we assume to operate in a single time zone, DATETIME is effectively insufficient.

Imagine this scenario:

1. A post is made at 1:30
2. Summer time stops at 2:00 and time jumps to 1:00 again
3. A post is made at 1:20
4. Now 1:20 posts is **younger**, while WP completely considers it to be **older**.

I follow your point that SQL can convert timezone on the fly. But we don't even know _which time zones posts are in_. It is essentially _individual per post_, so we _cannot_ do any bulk conversion.

## My preliminary ideas

I agree that _a time zone post was made in_ is valid and valuable data, that we can consider storing.

However I do not see how storage can be fixed, other than going to canonical UTC.

Roughly I think following things need to happen:

1. All post records **must** be created with valid UTC time
2. UTC time **should** be used as canonical whenever possible
3. We need to research if `WP_Post` can always work in UTC time internally
4. We need to consider date sort in queries to use UTC by default

**Comment by Rarst** [comment]
I had read and digest some more materials on the topic since and I came around on the issue of local times for the _future_ events.

While internal UTC representation is adequate and desirable for any _past_ moment of time, it is not adequate for scheduling _future_ events because of the impermanence of time zones.

For the moment I am considering to change focus to prevent/fix active breakage (such as ruined local times on time zone change in settings) and step away from the idea of canonical UTC.

**Comment by nylen** [comment]
Canonical UTC is still a good starting point for handling date/time data.

If you're concerned about future local times, then you also need to store a timezone identifier (the tzdata value like `America/Chicago`, not an offset), and possibly a flag indicating that "local time overrides UTC time if something changes".

If you're concerned about timezone boundaries changing over time, then you should probably store a _location_ instead of (or in addition to) the timezone identifier.

If you're concerned about leap seconds or other anomalies in UTC itself, good luck.

I wouldn't worry about any of these edge cases for blog software, to be honest.  I would still store the dates as canonical UTC and then use the blog's or the user's local timezone to interpret them.

This would not handle every edge case, but I think that's impossible anyway.  Canonical UTC would be worlds better than the way WP handles datetimes today.

**Comment by Rarst** [comment]
I'll need to review scheduling specifically, because it's a huge mess.

WP goes far beyond "blog software" and that's not a good premise to base design on.

I'd rather hold off on introducing a major change than mess it up. I am still picking up pieces from a mess with two different time zone systems and it literally took WP years to get to a place where that's practically viable.
